import React, { useState, useRef } from 'react';
import {
  Upload,
  FileCode,
  Play,
  RefreshCw,
  CheckCircle2,
  Code,
  Copy,
  Check,
  Info,
} from 'lucide-react';
import { AnalysisResponse, SamplePlanItem } from '../types';
import { formatINR, formatINRMonthly } from '../utils/currency';

interface PlanAnalyzerTabProps {
  samplePlans: SamplePlanItem[];
  selectedFilename: string;
  onSelectPlan: (filename: string) => void;
  rawJson: string;
  onChangeRawJson: (json: string) => void;
  onRunAnalysis: () => void;
  isAnalyzing: boolean;
  analysis: AnalysisResponse | null;
}

export const PlanAnalyzerTab: React.FC<PlanAnalyzerTabProps> = ({
  samplePlans,
  selectedFilename,
  onSelectPlan,
  rawJson,
  onChangeRawJson,
  onRunAnalysis,
  isAnalyzing,
  analysis,
}) => {
  const [activeInputTab, setActiveInputTab] = useState<'sample' | 'paste' | 'upload'>('sample');
  const [dragOver, setDragOver] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showRawJson, setShowRawJson] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = (file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const text = e.target?.result as string;
      onChangeRawJson(text);
      setActiveInputTab('paste');
    };
    reader.readAsText(file);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFileUpload(e.dataTransfer.files[0]);
    }
  };

  const handleCopyJson = () => {
    navigator.clipboard.writeText(rawJson);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Top Input Box */}
      <div className="p-5 rounded-xl bg-slate-900 border border-slate-800">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3 mb-4">
          <div>
            <h2 className="text-sm font-semibold text-white flex items-center gap-2">
              <FileCode className="w-4 h-4 text-indigo-400" />
              Terraform Plan Input
            </h2>
            <p className="text-xs text-slate-400">
              Upload or paste JSON generated by <code className="text-slate-300 font-mono">terraform show -json tfplan.binary</code>
            </p>
          </div>

          {/* Mode Switcher */}
          <div className="flex rounded-lg bg-slate-950 p-1 border border-slate-800 text-xs">
            <button
              onClick={() => setActiveInputTab('sample')}
              className={`px-3 py-1 rounded font-medium transition ${
                activeInputTab === 'sample' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Demo Plans
            </button>
            <button
              onClick={() => setActiveInputTab('upload')}
              className={`px-3 py-1 rounded font-medium transition ${
                activeInputTab === 'upload' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Upload File
            </button>
            <button
              onClick={() => setActiveInputTab('paste')}
              className={`px-3 py-1 rounded font-medium transition ${
                activeInputTab === 'paste' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              Paste JSON
            </button>
          </div>
        </div>

        {/* Input Modes */}
        {activeInputTab === 'sample' && (
          <div className="space-y-2">
            <label className="text-xs text-slate-300 font-medium block">
              Choose a Demo Terraform Plan:
            </label>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2.5">
              {samplePlans.map((p) => {
                const isSelected = p.filename === selectedFilename;
                return (
                  <button
                    key={p.filename}
                    onClick={() => onSelectPlan(p.filename)}
                    className={`p-3 rounded-lg text-left border transition ${
                      isSelected
                        ? 'bg-indigo-950/40 border-indigo-500/60'
                        : 'bg-slate-950 border-slate-800 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-mono font-bold text-white">{p.title}</span>
                      {isSelected && <CheckCircle2 className="w-3.5 h-3.5 text-indigo-400" />}
                    </div>
                    <p className="text-[11px] text-slate-400 mt-1 line-clamp-2">{p.description}</p>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {activeInputTab === 'upload' && (
          <div
            onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
            onDragLeave={() => setDragOver(false)}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
            className={`border-2 border-dashed rounded-lg p-8 text-center cursor-pointer transition ${
              dragOver ? 'border-indigo-500 bg-indigo-500/5' : 'border-slate-800 hover:border-slate-700 bg-slate-950'
            }`}
          >
            <input
              type="file"
              ref={fileInputRef}
              accept=".json"
              className="hidden"
              onChange={(e) => e.target.files?.[0] && handleFileUpload(e.target.files[0])}
            />
            <Upload className="w-6 h-6 text-slate-500 mx-auto mb-2" />
            <span className="text-xs font-medium text-slate-200 block">
              Click or drag Terraform plan JSON here
            </span>
            <span className="text-[11px] text-slate-500 mt-1 block">
              Accepts .json output from OpenTofu or Terraform
            </span>
          </div>
        )}

        {activeInputTab === 'paste' && (
          <div className="space-y-1.5">
            <div className="flex items-center justify-between text-xs text-slate-400">
              <span>Terraform Plan JSON:</span>
              <button onClick={handleCopyJson} className="hover:text-white flex items-center gap-1 text-[11px]">
                {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                {copied ? 'Copied' : 'Copy'}
              </button>
            </div>
            <textarea
              value={rawJson}
              onChange={(e) => onChangeRawJson(e.target.value)}
              rows={8}
              placeholder="Paste raw Terraform plan JSON..."
              className="w-full bg-slate-950 border border-slate-800 rounded-lg p-3 font-mono text-xs text-slate-200 focus:outline-none focus:ring-1 focus:ring-indigo-500"
            />
          </div>
        )}

        {/* Action Controls */}
        <div className="flex items-center justify-between gap-3 mt-4 pt-3 border-t border-slate-800">
          <button
            onClick={() => setShowRawJson(!showRawJson)}
            className="text-xs text-slate-400 hover:text-white flex items-center gap-1 px-2.5 py-1.5 rounded bg-slate-950 border border-slate-800"
          >
            <Code className="w-3.5 h-3.5" />
            <span>{showRawJson ? 'Hide JSON' : 'Inspect JSON'}</span>
          </button>

          <button
            onClick={onRunAnalysis}
            disabled={isAnalyzing || !rawJson.trim()}
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg font-semibold text-xs bg-indigo-600 hover:bg-indigo-500 text-white shadow transition disabled:opacity-50"
          >
            {isAnalyzing ? (
              <RefreshCw className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Play className="w-3.5 h-3.5 fill-white" />
            )}
            <span>Analyze Plan</span>
          </button>
        </div>

        {/* Inspect JSON Pane */}
        {showRawJson && (
          <div className="mt-3 p-3 bg-slate-950 rounded-lg border border-slate-800 max-h-60 overflow-y-auto font-mono text-[11px] text-slate-300">
            <pre>{rawJson}</pre>
          </div>
        )}
      </div>

      {/* Analysis Output Summary */}
      {analysis && (
        <div className="space-y-4">
          {/* Summary Counts Bar */}
          <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2">
            <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-center font-mono">
              <span className="text-[10px] text-slate-500 block uppercase">Detected</span>
              <span className="text-lg font-bold text-white">{analysis.resource_counts.total_detected}</span>
            </div>
            <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-center font-mono">
              <span className="text-[10px] text-slate-500 block uppercase">Billable</span>
              <span className="text-lg font-bold text-indigo-400">{analysis.resource_counts.billable}</span>
            </div>
            <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-center font-mono">
              <span className="text-[10px] text-slate-500 block uppercase">Skipped</span>
              <span className="text-lg font-bold text-slate-400">{analysis.resource_counts.skipped}</span>
            </div>
            <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-center font-mono">
              <span className="text-[10px] text-slate-500 block uppercase">Creates</span>
              <span className="text-lg font-bold text-emerald-400">{analysis.resource_counts.creates}</span>
            </div>
            <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-center font-mono">
              <span className="text-[10px] text-slate-500 block uppercase">Deletes</span>
              <span className="text-lg font-bold text-red-400">{analysis.resource_counts.deletes}</span>
            </div>
            <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-center font-mono">
              <span className="text-[10px] text-slate-500 block uppercase">Updates</span>
              <span className="text-lg font-bold text-amber-400">{analysis.resource_counts.updates}</span>
            </div>
            <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-center font-mono">
              <span className="text-[10px] text-slate-500 block uppercase">Replaced</span>
              <span className="text-lg font-bold text-purple-400">{analysis.resource_counts.replacements}</span>
            </div>
          </div>

          {/* Clean Non-Billable Notification */}
          {analysis.resource_counts.skipped > 0 && (
            <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 flex items-center gap-2 text-xs text-slate-400">
              <Info className="w-4 h-4 text-cyan-400 flex-shrink-0" />
              <span>
                Skipped <strong>{analysis.resource_counts.skipped} non-billable resources</strong> (resource groups, virtual networks, subnets, route tables) with ₹0 cost impact.
              </span>
            </div>
          )}

          {/* Extracted Resources List */}
          <div className="p-5 rounded-xl bg-slate-900 border border-slate-800">
            <h3 className="text-xs font-semibold text-slate-200 uppercase tracking-wider font-mono mb-3">
              Detected Changes
            </h3>

            <div className="space-y-2">
              {analysis.resource_details.map((res, i) => {
                const isSkipped = res.status === 'SKIPPED';
                return (
                  <div
                    key={i}
                    className={`p-3 rounded-lg border flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs font-mono ${
                      isSkipped ? 'bg-slate-950/60 border-slate-800/60 opacity-60' : 'bg-slate-950 border-slate-800'
                    }`}
                  >
                    <div>
                      <div className="flex items-center gap-2">
                        <span
                          className={`px-1.5 py-0.5 rounded text-[10px] font-bold ${
                            res.action === 'CREATE'
                              ? 'bg-emerald-500/10 text-emerald-400'
                              : res.action === 'DELETE'
                              ? 'bg-red-500/10 text-red-400'
                              : res.action === 'UPDATE'
                              ? 'bg-amber-500/10 text-amber-400'
                              : res.action === 'REPLACEMENT'
                              ? 'bg-purple-500/10 text-purple-400'
                              : 'bg-slate-800 text-slate-400'
                          }`}
                        >
                          {res.action}
                        </span>
                        <span className="text-slate-200 font-semibold">{res.address}</span>
                      </div>
                      <div className="text-[11px] text-slate-500 mt-1">
                        SKU: {res.sku} &bull; Region: {res.region}
                      </div>
                    </div>

                    <div className="text-right">
                      <div
                        className={`font-bold ${
                          isSkipped
                            ? 'text-slate-500'
                            : res.delta_monthly_cost > 0
                            ? 'text-amber-400'
                            : res.delta_monthly_cost < 0
                            ? 'text-emerald-400'
                            : 'text-slate-400'
                        }`}
                      >
                        {isSkipped
                          ? 'SKIPPED'
                          : formatINRMonthly(res.delta_monthly_cost, { showSign: true, fullUnit: true })}
                      </div>
                      {!isSkipped && (
                        <div className="text-[10px] text-slate-500">
                          {formatINR(res.old_monthly_cost)} → {formatINR(res.new_monthly_cost)}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Simple Why Did Cost Change Explanation */}
          {analysis.explanations && analysis.explanations.length > 0 && (
            <div className="p-5 rounded-xl bg-slate-900 border border-slate-800">
              <h3 className="text-xs font-semibold text-slate-200 uppercase tracking-wider font-mono mb-2">
                Why Did Cost Change?
              </h3>
              <ul className="space-y-1.5 text-xs text-slate-300">
                {analysis.explanations.map((exp, idx) => (
                  <li key={idx} className="flex items-start gap-2">
                    <span className="text-indigo-400 font-bold">•</span>
                    <span>{exp}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
